---
- name: Create directory /etc/systemd/resolved.conf.d/
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: Copy dns.conf to /etc/systemd/resolved.conf.d/
  template:
    src: dns.conf.j2
    dest: /etc/systemd/resolved.conf.d/dns.conf
  notify: restart systemd-resolved
