---
- name: Set net.ipv6.conf.all.disable_ipv6
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "{{ common_security_disable_ipv6 }}"
    sysctl_set: yes
    state: present
    reload: yes

- name: Set net.ipv6.conf.default.disable_ipv6
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: "{{ common_security_disable_ipv6 }}"
    sysctl_set: yes
    state: present
    reload: yes

- name: Set net.ipv6.conf.lo.disable_ipv6
  ansible.posix.sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: "{{ common_security_disable_ipv6 }}"
    sysctl_set: yes
    state: present
    reload: yes